spring.application.name=mutual-funds-backend

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/mutual_funds_app?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=Root@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info

app.live-nav.enabled=true
app.live-nav.url=https://portal.amfiindia.com/spages/NAVAll.txt
app.live-nav.cron=0 30 18 * * MON-FRI
